### ISSUE TITLE
Openssl 3  installed in cygwin

### ISSUE THREAD

**Issue by ghost** [justdan96/cygwin-openssl3#1]
Hi.  friend
Because cygwin does not support openssl>3.0,  I found your here
In order to install openssl >3.0 in cygwin, I tried various methods and failed
How to install your new version in cygwin ?    thanks
Can  give an example

**Comment by justdan96** [comment]
I haven't looked at this for a while - last release was February of last year as you can see - but it would just be to extract the ZIP file from that release to your Cygwin directory structure https://github.com/justdan96/cygwin-openssl3/releases/download/v3.0.1/openssl3.zip

**Comment by justdan96** [comment]
Actually I've just updated the repo, so now this is the latest release: https://github.com/justdan96/cygwin-openssl3/releases/tag/v3.1.0

**Comment by ghost** [comment]
@justdan96
Ok thanks
